---
namespace: "sedunne"
name: "simple"
version: "1.3.1"
readme: "README.md"
authors:
  - "Stephen Dunne"
license:
  - "MIT"
tags:
  - collection
  - server
  - firewall
  - livepatch
  - ubuntu
  - debian
  - wireguard
  - iptables
  - ipv6
repository: "https://github.com/sedunne/ansible-collection-simple"
