---
namespace: "sedunne"
name: "simple"
version: "0.0.3"
readme: "README.md"
authors:
  - "Stephen Dunne"
license:
  - "MIT"
tags:
  - collection
  - server
  - firewall
  - livepatch
repository: "https://github.com/sedunne/ansible-collection-simple"
