---
- name: "Install iptables persistent package"
  ansible.builtin.package:
    name: "iptables-persistent"
    state: "present"

- name: "Template iptables v4 configuration"
  ansible.builtin.template:
    src: rules_v4.j2
    dest: "/etc/iptables/rules.v4"
    owner: "root"
    group: "root"
    mode: "0640"
  notify:
    - Restart iptables

- name: "Template iptables v6 configuration"
  ansible.builtin.template:
    src: rules_v6.j2
    dest: "/etc/iptables/rules.v6"
    owner: "root"
    group: "root"
    mode: "0640"
  notify:
    - Restart iptables

- name: "Start iptables"
  ansible.builtin.service:
    name: "{{ iptables_service_name[ansible_distribution] }}"
    state: "started"
    enabled: true
