---
galaxy_info:
  role_name: wireguard
  author: Stephen Dunne
  description: 'Deploy Wireguard VPN Tunnel'
  license: MIT
  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags:
    - server
    - ubuntu
    - debian
    - wireguard

dependencies: []
