---
- name: Set IPv4 Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

- name: Install Wireguard KMod
  ansible.builtin.package:
    state: "present"
    name: "{{ wireguard_packagename }}"
  when: ansible_kernel is version('5.6', '<')

## this is usually a dep of the above, but since it's built into 5.6+ kernels,
##   we sometimes just need this package.
- name: Install Wireguard Tools
  ansible.builtin.package:
    state: "present"
    name: "{{ wireguard_toolspackagename }}"

## sometimes the interface needs to be added, but the config doesn't change, leaving the interface unconfigured.
## adding the notify at the end should hopefully fix that.
- name: Add wg0 Interface
  ansible.builtin.shell: ip link add dev wg0 type wireguard
  when: "'wg0' not in ansible_interfaces"
  notify: "wg syncconf"

- name: Wireguard Generate Keys
  ansible.builtin.shell: cd /etc/wireguard; wg genkey | tee privatekey | wg pubkey > publickey
  args:
    creates: /etc/wireguard/privatekey

- name: Set Permissions on Private Key
  ansible.builtin.file:
    path: /etc/wireguard/privatekey
    mode: '0600'
    owner: root
    group: root

- name: Read Private Key
  ansible.builtin.command: cat /etc/wireguard/privatekey
  register: wg_key_private

- name: Template Wireguard Config
  ansible.builtin.template:
    src: wg0_conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: "wg syncconf"
